### ISSUE TITLE
Trouble Using "Start Job" Process in Plugin

### ISSUE THREAD

**Issue by bostonhawk86** [UrbanCode/Jenkins-Job-Manager-UCD#1]
I'm trying to run the "Start Job" step using the Jenkins Job Manager plugin in Deploy 7.0.2. I keep getting an HTTP 403 error which means Deploy cannot authenticate with the Jenkins instance. However, if I run the exact command from a DOS window logged into the server as that user, it runs fine. It just doesn't work using the Deploy agent. Might have something to do with running it through Java.  This is the error:

[Action] Running Command: java -jar <jenkins-cli.jar> -s http://jenkins-stage build /QA/Adaptavist_Compile -f -v --username mason_d --password ****
Caught: java.io.EOFException
java.io.EOFException
	at hudson.cli.CLI.connectViaCliPort(CLI.java:232)
	at hudson.cli.CLI.<init>(CLI.java:128)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:479)
	at hudson.cli.CLI$_main.call(Unknown Source)
	at jenkinsJobManager.startJob(jenkinsJobManager.groovy:60)
	at jenkinsJobManager$startJob.callCurrent(Unknown Source)
	at jenkinsJobManager.run(jenkinsJobManager.groovy:26)
	Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://jenkins-stage/cli

Any assistance would be greatly appreciated

**Comment by nhmathis** [comment]
1) I would double check for invalid/special characters in your password, such as spaces or !@#$%^&*(). 

2) The CLI imported into the plugin is fairly old: [link](https://github.com/UrbanCode/Jenkins-Job-Manager-UCD/blob/master/build.gradle#L55)
`compile group: 'org.jenkins-ci.main', name: 'cli', version: '1.651.3' `

Likely, when you are running it locally on the Jenkins server, it's referencing a compatible CLI version. 

You might need to rebuild the plugin using a compatible CLI with your version of Jenkins.
See here for updated versions: https://mvnrepository.com/artifact/org.jenkins-ci.main/cli

However, I do not know if the updated CLI will break the issues in other ways. 

Can you respond with what version of the Jenkins CLI you are currently running?

**Comment by bostonhawk86** [comment]
While I do have special characters in my password, if I run the command through the command line, it works fine.  The plugin prints out the command in the output log.  I used cut-and-paste to run the command through the shell plugin and that works, no problem.  So I think you’re on the right track about the version of the CLI that’s imported in to the plugin.  Our Jenkins instance is using version 2.121.3-cb-1.  Does that help?  Also, how do I rebuild the plugin with a compatible CLI?

**Comment by bostonhawk86** [comment]
Sorry for another email , but I think you’re on to something.  Yes, in the plugin, there is a cli-1.651.3.jar file.  That’s what the plugin must be using to connect to Jenkins.  The reason it works from the command line is that I downloaded my CLI file and put it in C:\Jenkins on the server.  I ran the command from THAT directory using THAT CLI, not the one in the plugin.  So I think you’re right, if I rebuild the plugin with my newer version of the CLI, it should work.  How do I rebuild the plugin?

**Comment by nhmathis** [comment]
Hi,

Steps to fix:
1. In the `build.gradle`, modify the version in this line `compile group: 'org.jenkins-ci.main', name: 'cli', version: '1.651.3'` to `2.121.3`. (I'm not sure where you found the extra `cb-1` extension, but I don't think that version is available through maven central.)
2. To build the plugin, run `gradle` in the root directory. Note: You will need the `gradle` tool installed. https://gradle.org/

-Nick
